<?php

//	Form name index
define('form_name',             'form-name');

//  Login state
define('session_state',         'session_state');
define('ss_is_logged_in',       'ss_is_logged_in');
define('ss_not_logged_in',      'ss_not_logged_in');
define('remember_me',           'remember_me');
define('need_password',         'need_password');
define('password',              'password');
define('new_password',          'new_password');
define('repeat_new',            'repeat_new');

//  Person and his/her department choice
define('person',                'person');
define('preferred_dept_index',  'preferred_dept_index');

//  Error messages
define('bad_email',             'Unrecognized email address');
define('no_dept',               'Unknown department affiliation');

//  Catalog information (class Proposal)
define('course_title',          'course_title');
define('components',            'components');
define('credits',               'credits');
define('prerequisites',         'prerequisites');
define('catalog_description',   'catalog_description');
define('designation',           'designation');
define('justifications',        'justifications');
define('with_approvals',        'with_approvals');

//  Course String RegEx
define('course_str_re',         '/^\s*([a-z]{2,6})\s*\-?\s*([1-9]\d{0,3}[wh]?)\s*$/i');
//  Proposal ID ranges
define('MAX_PLAS_ID',           '160');


?>