<?php

//  Atoms used only by Proposal Manager
//  =====================================================================================
/*  Use the following defines instead of the corresponding strings.
 *  The compiler will report if the strings are spelled wrong, and the actual string
 *  values can be managed from this file.
 *
 *  Convention:
 *    HTML and CSS (classes and ids) use hyphens; PHP everything else uses underscores.
 */

  //  Proposal Form names
  define('select_proposal',       'select-proposal');
  define('create_proposal',       'create-proposal');
  define('select_one_course',     'select-one-course');
  define('edit_course',           'edit-course');
  define('edit_designation',      'edit-designation');
  define('do_it',                 'do-it');
  define('syllabus_upload',       'syllabus-upload');

  //  Select proposal form data
  define('use_proposal',          'use_proposal');
  define('course_str',            'course_str');
  define('proposal_type',         'proposal_type');

  //  Error messages
  define('error_msg',             'error_msg');

  //  $_SESSION variables
  define('proposal',              'proposal');
  define('cur_catalog',           'cur_catalog');
  define('new_catalog',           'new_catalog');
  define('course_array',          'course_array');
  define('course_index',          'course_index');

  //  Prompt value for proposal type selector
  define('select_proposal_type',  'Select the proposal type');

  define('course_proposal_type',  'course-proposal-type');
  define('proposal_type_radio',   'proposal-type-radio');
  define('new_course',            'new-course');
  define('revise_course',         'revise-course');
  define('fix_course',            'fix-course');

?>
